### ISSUE TITLE
ART Commencement Form: Missing Concept ID in the Dictionary

### ISSUE THREAD

**Issue by elameen221** [nmrs-nigeria/openmrs-module-nigeriaemr#89] opened 2019-08-26 17:33 UTC
ART Commencement Form
The INH Stop date concept id <td><obs conceptId="166096"/></td> is currently not in the concept dictionary, the data migration team would need to include this ID in the dictionary for this field to be activated.

 @elameen221

**Comment by ahmedsylvanus** [comment] 2019-08-28 10:25
This is a duplicate of Issue 90

**Closed** 2019-08-28 10:25 UTC
